import localFont from 'next/font/local'
import './globals.css'
import Navbar from '@/components/ui/NavBar'
import { LoginProvider } from '@/context/LoginContext'
import { ReservaProvider } from '@/context/ReservaContext'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata = {
  title: 'AirPorter',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <LoginProvider>
          <ReservaProvider>
            <Navbar />

            {children}
          </ReservaProvider>
        </LoginProvider>
      </body>
    </html>
  )
}
